system linux-guest-v6
ram 0x80000000,512m
cpu
cpu
guest load /dev/shmem/linux-Image
initrd load /dev/shmem/initrd-v6.gz
cmdline "console=ttyAMA0 earlycon=pl011,0x1c090000 loglevel=8 init=/init"

vdev vdev-pl011
 loc 0x1c090000
 intr gic:37
 hostdev >/data/linux-v6-console.log

vdev virtio-blk
 loc 0x1c0c0000
 intr gic:40
 hostdev /data/linux-trace.img
 name trace-disk

vdev vdev-virtio-net
 loc 0x1c0b0000
 intr gic:39
 name p2p
 peer /dev/vdevpeers/vp0
 peerfeats 0x3
